#!/bin/bash
# - (dash separator): Simple script to print out a separator line in terminal
# Copyright (C) 2013 by Yu-Jie Lin
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
#
# Gist: https://gist.github.com/livibetter/6059720
# Blog: http://blog.yjl.im/2013/07/dash-separator-for-terminal-output.html 

declare -A CTBL

CTBL=(
  [k]='0m'    [black]='0m'  [bk]='0;1m'    [brightblack]='0;1m'
  [r]='1m'      [red]='1m'  [br]='1;1m'      [brightred]='1;1m'
  [g]='2m'    [green]='2m'  [bg]='2;1m'    [brightgreen]='2;1m'
  [y]='3m'   [yellow]='3m'  [by]='3;1m'   [brightyellow]='3;1m'
  [b]='4m'     [blue]='4m'  [bb]='4;1m'     [brightblue]='4;1m'
  [m]='5m'  [magenta]='5m'  [bm]='5;1m'  [brightmagenta]='5;1m'
  [c]='6m'     [cyan]='6m'  [bc]='6;1m'     [brightcyan]='6;1m'
  [w]='7m'    [white]='7m'  [bw]='7;1m'    [brightwhite]='7;1m'
)

help() {
  echo "Usage: $(basename $0) [OPTION]...

Options:
  -c  change separator character
  -u  change separator character to '─'
  -f  change foreground color
  -b  change background color
  -M  do not move cursor up

Colors: ${!CTBL[@]}, or something like '1;33m'
" | fold
}

W=$(tput cols)
printf -v SEP '%*s' $W
C='-'

while getopts :c:uf:b:M opt; do
  case $opt in
    c)
      C=$OPTARG
      ;;
    u)
      C='─'
      ;;
    f)
      F=3${CTBL[$OPTARG]}
      [[ $F = 3 ]] && F=$OPTARG
      ;;
    b)
      B=4${CTBL[$OPTARG]}
      [[ $B = 4 ]] && B=$OPTARG
      ;;
    M)
      M=1
      ;;
    *)
      help
      exit 1
      ;;
  esac
done

[[ $M ]] || echo -ne "\e[1F"
[[ $F ]] && echo -ne "\e[$F"
[[ $B ]] && echo -ne "\e[$B"
SEP="${SEP// /$C}"
echo "${SEP::W}"
[[ $F ]] || [[ $B ]] && echo -ne "\e[0m" || :
